FROM ubuntu:18.04

LABEL image=yantian/webapp-ubuntu18:v1

ARG BRANCH=master

# GIT repo directory
ENV REPOS_DIR="/home/Webapp" 

# Webapp repo
ENV MYSITE_REPO_DIR="${REPOS_DIR}/mysite"

RUN apt-get update && \
    apt-get install -y git python3 python3-setuptools python3-dev python3-pip virtualenv wget curl && \
    apt-get -y autoremove && \
    apt-get clean

RUN pip3 install pyopenssl==17.5.0

# pull the webapp for github
RUN git config --global http.sslVerify false
RUN git clone --depth 1 -b $BRANCH https://github.com/You-yantian/Webapp.git ${REPOS_DIR}

# install the required packages
RUN pip3 install -r ${REPOS_DIR}/requirements.txt

# migrate any updates in the database
RUN python3 ${MYSITE_REPO_DIR}/manage.py makemigrations
RUN python3 ${MYSITE_REPO_DIR}/manage.py migrate

EXPOSE 8080

# Set work directory
WORKDIR ${MYSITE_REPO_DIR}