FROM ubuntu:18.04

LABEL image=yantian/webapp-ubuntu18:v1

ARG BRANCH=master

# GIT repo directory
ENV REPOS_DIR="/home" 

# Set work directory

# Webapp repo
ENV WEBAPP_REPO_DIR="${REPOS_DIR}/webapp/"

RUN apt-get update && \
    apt-get install -y git python3 python3-setuptools python3-dev python3-pip virtualenv wget curl && \
    apt-get -y autoremove && \
    apt-get clean

RUN pip3 install pyopenssl==17.5.0

# pull the webapp for github
RUN git config --global http.sslVerify false
RUN git clone --depth 1 -b $BRANCH https://github.com/You-yantian/Webapp.git ${WEBAPP_REPO_DIR}

# config virtual environment and activate it
RUN virtualenv django
RUN source /home/django/bin/activate

# install the required packages
RUN pip3 install -r ${WEBAPP_REPO_DIR}/requirements.txt

# migrate any updates in the database
RUN python3 manage.py makemigrations
RUN python3 manage.py migrate

# start the webserver
RUN python3 manage.py runserver 0:8080

EXPOSE 8080

WORKDIR ${REPOS_DIR}